version: '2'
services:
    bmsservernew:
      image: node:6.11.2
      restart: always
      command: node --max-old-space-size=8192 ./index.js
      working_dir: /app
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - /root/bms/deploy/restfulsrv:/app
        - /root/bms/deploy/kafkadb/node_docker:/app/node_modules/node-rdkafka/build/Release
        - /root/bms/deploy/dist/log:/log
        - /root/bms/deploy/dist/uploader:/uploader
      environment:
        - DEBUG=srvapp:*,-mquery
        - DEBUG_COLORS=1
        - MONGO_URL=mongodb://192.168.2.18:12017,192.168.2.13:12017,192.168.2.14:12017,192.168.2.15:12017/bmscatl?readPreference=secondaryPreferred
        - KAFKA_HOST=192.168.2.11:9092,192.168.2.12:9092,192.168.2.13:9092
        - listenport=5012
        - mongos=true
        - mysqlhost=192.168.2.14
        - rooturl=http://121.204.130.141:81
        - logdir=/log
        - uploaddir=/uploader
      network_mode: "host"
      ports:
         - "5012:5012"
      expose:
         - "5012"
