version: '2'
services:
  kafkamanager:
      image: sheepkiller/kafka-manager:latest
      restart: always
      ports:
        - "9000:9000"
      environment:
        - ZK_HOSTS=172.26.175.131:2181,172.26.175.132:2181,172.26.175.133:2181
        - APPLICATION_SECRET=letmein
