docker-compose -f ./kafkadb111.yml up -d
docker-compose -f ./kafkadb112.yml up -d
docker-compose -f ./kafkadb113.yml up -d
docker-compose -f ./kafkadb114.yml up -d
docker-compose -f ./kafkadb115.yml up -d
docker-compose -f ./kafkadb116.yml up -d
docker-compose -f ./kafkadb117.yml up -d
docker-compose -f ./kafkadb118.yml up -d
docker-compose -f ./kafkadb211.yml up -d
docker-compose -f ./kafkadb212.yml up -d
docker-compose -f ./kafkadb213.yml up -d
docker-compose -f ./kafkadb214.yml up -d
docker-compose -f ./kafkadb215.yml up -d
docker-compose -f ./kafkadb216.yml up -d
docker-compose -f ./kafkadb217.yml up -d
docker-compose -f ./kafkadb218.yml up -d
docker-compose -f ./kafkadb311.yml up -d
docker-compose -f ./kafkadb312.yml up -d
docker-compose -f ./kafkadb313.yml up -d
docker-compose -f ./kafkadb314.yml up -d
docker-compose -f ./kafkadb315.yml up -d
docker-compose -f ./kafkadb316.yml up -d
docker-compose -f ./kafkadb317.yml up -d
docker-compose -f ./kafkadb318.yml up -d
docker-compose -f ./kafkadb411.yml up -d
docker-compose -f ./kafkadb412.yml up -d
docker-compose -f ./kafkadb413.yml up -d
docker-compose -f ./kafkadb414.yml up -d
docker-compose -f ./kafkadb415.yml up -d
docker-compose -f ./kafkadb416.yml up -d
docker-compose -f ./kafkadb417.yml up -d
docker-compose -f ./kafkadb418.yml up -d
docker-compose -f ./kafkadb511.yml up -d
docker-compose -f ./kafkadb512.yml up -d
docker-compose -f ./kafkadb513.yml up -d
docker-compose -f ./kafkadb514.yml up -d
docker-compose -f ./kafkadb515.yml up -d
docker-compose -f ./kafkadb516.yml up -d
docker-compose -f ./kafkadb517.yml up -d
docker-compose -f ./kafkadb518.yml up -d
