docker-compose -f ./kafkadb111.yml up -d
docker-compose -f ./kafkadb112.yml up -d
docker-compose -f ./kafkadb113.yml up -d
docker-compose -f ./kafkadb114.yml up -d
docker-compose -f ./kafkadb115.yml up -d
docker-compose -f ./kafkadb116.yml up -d
docker-compose -f ./kafkadb117.yml up -d
docker-compose -f ./kafkadb118.yml up -d
docker-compose -f ./kafkadb211.yml up -d
docker-compose -f ./kafkadb212.yml up -d
docker-compose -f ./kafkadb213.yml up -d
docker-compose -f ./kafkadb214.yml up -d
docker-compose -f ./kafkadb215.yml up -d
docker-compose -f ./kafkadb216.yml up -d
docker-compose -f ./kafkadb217.yml up -d
docker-compose -f ./kafkadb218.yml up -d
docker-compose -f ./kafkadb311.yml up -d
docker-compose -f ./kafkadb312.yml up -d
docker-compose -f ./kafkadb313.yml up -d
docker-compose -f ./kafkadb314.yml up -d
