docker-compose -f ./kafkadb315.yml up -d
docker-compose -f ./kafkadb316.yml up -d
docker-compose -f ./kafkadb317.yml up -d
docker-compose -f ./kafkadb318.yml up -d
docker-compose -f ./kafkadb411.yml up -d
docker-compose -f ./kafkadb412.yml up -d
docker-compose -f ./kafkadb413.yml up -d
docker-compose -f ./kafkadb414.yml up -d
docker-compose -f ./kafkadb415.yml up -d
docker-compose -f ./kafkadb416.yml up -d
docker-compose -f ./kafkadb417.yml up -d
docker-compose -f ./kafkadb418.yml up -d
docker-compose -f ./kafkadb511.yml up -d
docker-compose -f ./kafkadb512.yml up -d
docker-compose -f ./kafkadb513.yml up -d
docker-compose -f ./kafkadb514.yml up -d
docker-compose -f ./kafkadb515.yml up -d
docker-compose -f ./kafkadb516.yml up -d
docker-compose -f ./kafkadb517.yml up -d
docker-compose -f ./kafkadb518.yml up -d
