version: '2'
services:
  bmsshardres1bk:
    container_name: bmsshardres1bk
    image:  mongo:3.4
    restart: always
    command: mongod --shardsvr --replSet bmsshardres1 --dbpath /data/db --port 22001
    ports:
      - 22001:22001
    expose:
      - "22001"
    environment:
      TERM: xterm
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /catlcluster/mongo_cluster/bmsshardres1/db:/data/db
