version: '2'
services:
  kafkamanager:
      image: sheepkiller/kafka-manager:latest
      restart: always
      ports:
        - "9000:9000"
      environment:
        - ZK_HOSTS=192.168.2.11:2181,192.168.2.12:2181,192.168.2.13:2181
        - APPLICATION_SECRET=letmein
        - KM_ARGS=Djava.net.preferIPv4Stack=true
